### ISSUE TITLE
The server start but no file is rendered

### ISSUE THREAD

**Issue by KabbAmine** [turbio/bracey.vim#1]
Your plugin looks very promising but unfortunately its not working for me :cry: 

## Steps to reproduce

1. Install the plugin via vim-plug and the node modules using vim-plug's post-update hook (`Plug 'turbio/bracey.vim', {'do': 'npm install --prefix bracey'}`).
2. I create a new file `t.html` in vim and put some content in it.
3. I launch bracey using `:Bracey`.
4. My browser (Firefox) is opened and the bracey server starts but no file found:

![bracey](https://cloud.githubusercontent.com/assets/5658084/14409820/bcec6066-ff26-11e5-9432-20b97d0c0163.png)

No javascript related errors in the console also.

## Configuration

Vim 7.4.882
Xubuntu 14.04.04
Node 4.4.2

Did I miss something?
It will be awesome to make bracey work, so I can replace `browser-sync` for static files.

**Comment by turbio** [comment]
My best guess is you don't have python3 installed which is currently required to send http requests to the bracey server. Right now, if you don't have python3, it will just silently fail to make any http requests and thus the server will sit there doing nothing. It's planned to have it fall back to python2 and then just plain curl  but that has yet to be implemented.

Right now the plugins in a really rough state and has only been tested to work in my very specific setup.

**Comment by KabbAmine** [comment]
I have python3 installed but my vim version is not compiled with it.
Anyway, I'll close this issue until a beta/1.0 version of bracey will be available (I'm following your repo), so take your time :smiley:
