### ISSUE TITLE
How do I use the Configs

### ISSUE THREAD

**Issue by LGKev** [turbio/bracey.vim#10]
Hi I do not understand how to use the g:bracey_eval_on_save. I started :Bracey within an html file and it loads the page, but I would like to change the default for bracey_eval_on_save. How do I do so?

**Comment by turbio** [comment]
Bracey's `g:bracey_eval_on_save` flag controls whether or not saving a javascript file will cause it to be evaluated in the browser. You can set it to `0` in your vimrc if you'd like to disable The feature, it's enabled by default. I don't believe there is any support for evaluating scripts embedded in html.
