### ISSUE TITLE
bracey  server error?

### ISSUE THREAD

**Issue by heguohui2018** [turbio/bracey.vim#11]
Hello ! How can I solve this problem?
my using MacOS
this my init.vim config
<img width="1005" alt="1" src="https://user-images.githubusercontent.com/35359288/66570252-d2c58c00-eb9f-11e9-97e9-965757568bf3.png">

run command error

<img width="1334" alt="2" src="https://user-images.githubusercontent.com/35359288/66570282-e113a800-eb9f-11e9-83d8-f24ba4558bf8.png">

<img width="1280" alt="3" src="https://user-images.githubusercontent.com/35359288/66570303-ec66d380-eb9f-11e9-8740-ea5f491b6003.png">

**Comment by turbio** [comment]
hey @heguohui2018 thanks for reporting 
looks like you ran `npm` in your home directory. Could you try instead running `npm install --prefix server` inside the plugin's install directory.

the installation section should have more information on this: https://github.com/turbio/bracey.vim#installation

**Comment by heguohui2018** [comment]
Thank you ,
I try,but server error

**Comment by turbio** [comment]
fixed https://github.com/turbio/bracey.vim/pull/18
