### ISSUE TITLE
“connetion” typo in bracey.py script

### ISSUE THREAD

**Issue by adambrault** [turbio/bracey.vim#12]
I’ve been trying to figure out why remote access won’t work for me. Haven’t quite figured that out yet, but I just noticed there is a typo in this line which would likely prevent it regardless:

https://github.com/turbio/bracey.vim/blob/2a2a65029d7a305ca2b48042d0b325a1a3f6ad8f/script/bracey.py#L39

If I’m able to track down what’s not working with remote access, I’ll create a pull request for that.

**Comment by turbio** [comment]
thanks for the reporting, should be fix in master now
