### ISSUE TITLE
[May not be an issue] Server breaks when I switch buffer, spit window etc.

### ISSUE THREAD

**Issue by Godnyx** [turbio/bracey.vim#20]
I will try to explain the problem. So I open my html file and then I type :Bracey and everything works great. But if I do things like change buffer, split the window or change to another window (were it was already opened before the ":Bracey" command) then the server will suddenly break!

I don't understand why this happens. Isn't the server connected with the file itself? Or is it connected with the current vim's view so when I change the current file that is displayed, it causes the server to break? Anyway, the real question is how can I fix that? In real time I would have multiple windows open and I will change between them and I can't have to server to always break. Also I have to mention that that's the default Bracey behavior cause I haven't changed anything and I use the default config!

**Edit:** Well guess what... After uploading this, I was about to give another try (even tho I tried many times) just for fun and to mess around. An well... It magically works now! So I'm sorry for the mess. I'm gonna close the issue. And if this problem appears again, I'll make sure to inform you! Have a great day sir!

**Comment by vimovernano** [comment]
I was having the same exact issues and now I am curious as to what magically fixed it for you. Could it be conflicting configs with how the network is set up?

The plugin is great, unfortunately I am going to have to set it aside until I can figure out why it is dropping out for me. I only recently swapped to Debian, so I figured it was most likely on my end.

**Comment by cjnucette** [comment]
I've found that if I open the buffers with `:e` instead for example with `coc-explorer`, it works; otherwise, it breaks.

**Comment by Godnyx** [comment]
> I was having the same exact issues and now I am curious as to what magically fixed it for you. Could it be conflicting configs with how the network is set up?
> 
> The plugin is great, unfortunately I am going to have to set it aside until I can figure out why it is dropping out for me. I only recently swapped to Debian, so I figured it was most likely on my end.

Sorry for not answering, I didn't got any notification for that. I found it today from another guy (big story). Have your problem being fixed?

**Comment by mirsella** [comment]
same problem for me, but it work if i open another file with :e instead of vim -p
i hope someone can look into it
thanks

**Comment by svanke** [comment]
Hey, so I guess this is the end for this issue. Such a shame as it would probably one of the best plugin for live edit options on nvim. You can make it work with specific workaround, like not using any other methods to open/create files except :e, start in cwd, restarting Bracey again and etc. but it's super annoying and makes to give up on this plugin... and it's such a shame as it's has so many advantages over using npm live-server...

**Comment by beyond9thousand** [comment]
I can't even get it to work with nvim, how are you guys making it work?

**Comment by rempas** [comment]
> I can't even get it to work with nvim, how are you guys making it work?

I don't know about the others but I haven't tried it in a long time.

**Comment by beyond9thousand** [comment]
That's a bummer, really needed a smoother method of doing this

**Comment by Hishantik** [comment]
add this line in your init.lua config file 

~~~
vim.g.python3_host_prog = "/usr/bin/python3" -- Adjust path if needed (e.g., /usr/local/bin/python3)

-- Helper function to determine the project root

local function find_project_root()
  local file_dir = vim.fn.expand("%:p:h")
  local path_parts = vim.split(file_dir, "/")
  for i = #path_parts, 1, -1 do
    local potential_root = table.concat(path_parts, "/", 1, i)
    if vim.fn.filereadable(potential_root .. "/index.html") == 1 then
      return potential_root
    end
  end
  return vim.fn.fnamemodify(file_dir, ":h")
end

-- Set project root as global CWD at startup
vim.api.nvim_create_autocmd("VimEnter", {
  pattern = "*.html",
  callback = function()
    local project_root = find_project_root()
    vim.cmd("cd " .. project_root) -- Set global CWD
    vim.cmd("Bracey")              -- Start bracey automatically
  end,
  once = true,
})


vim.api.nvim_create_autocmd("BufEnter",
  {
    pattern = { "*" },
    callback = function()
      vim.cmd("lcd " .. vim.fn.expand("%:p:h"))
    end,
  })


-- Clean up bracey server on exit
vim.api.nvim_create_autocmd("VimLeave", {
  callback = function()
    vim.cmd("BraceyStop")
  end,
 })

~~~
~~~

**Comment by rempas** [comment]
> add this line in your init.lua config file
> 
> ```
> vim.g.python3_host_prog = "/usr/bin/python3" -- Adjust path if needed (e.g., /usr/local/bin/python3)
> 
> -- Helper function to determine the project root
> 
> local function find_project_root()
>   local file_dir = vim.fn.expand("%:p:h")
>   local path_parts = vim.split(file_dir, "/")
>   for i = #path_parts, 1, -1 do
>     local potential_root = table.concat(path_parts, "/", 1, i)
>     if vim.fn.filereadable(potential_root .. "/index.html") == 1 then
>       return potential_root
>     end
>   end
>   return vim.fn.fnamemodify(file_dir, ":h")
> end
> 
> -- Set project root as global CWD at startup
> vim.api.nvim_create_autocmd("VimEnter", {
>   pattern = "*.html",
>   callback = function()
>     local project_root = find_project_root()
>     vim.cmd("cd " .. project_root) -- Set global CWD
>     vim.cmd("Bracey")              -- Start bracey automatically
>   end,
>   once = true,
> })
> 
> 
> vim.api.nvim_create_autocmd("BufEnter",
>   {
>     pattern = { "*" },
>     callback = function()
>       vim.cmd("lcd " .. vim.fn.expand("%:p:h"))
>     end,
>   })
> 
> 
> -- Clean up bracey server on exit
> vim.api.nvim_create_autocmd("VimLeave", {
>   callback = function()
>     vim.cmd("BraceyStop")
>   end,
>  })
> ```

I'm currently developing with Vite so, there is no need for this plugin but thank you so much for taking the time to write this for me and everyone else that might need it!
