### ISSUE TITLE
Bracey doesn't stop the web server once vim is closed

### ISSUE THREAD

**Issue by Aayush9029** [turbio/bracey.vim#24]
The node launch.js file needs to stop once the terminal is closed.

![Screen Shot 2020-04-30 at 9 29 19 PM](https://user-images.githubusercontent.com/43297314/80774107-0b23bc00-8b2a-11ea-830e-983781128deb.png)

Here we can see the node launch.js is open despite vim session being closed.

**Comment by turbio** [comment]
Could you provide some details about the system you're running Bracey on? When running normally, is the bracey node server a child of vim?
Looks like you're on MacOS which I'm not particularly familiar with, sounds like its not getting the signal it expects when vim exits.

**Comment by Aayush9029** [comment]
I am running on macOS. I added a custom script that stops all node services
 once I quit vim. So it’s partially solved for now

**Comment by apchirinoc** [comment]
Hello, how can I close the environments I did't stop with :BraceyStop?
