### ISSUE TITLE
Bracy showing error of python

### ISSUE THREAD

**Issue by AmanAjayVarma** [turbio/bracey.vim#29]
![Screenshot from 2020-05-04 07-38-19](https://user-images.githubusercontent.com/50282743/80931880-3fbd9f00-8dda-11ea-8e22-c8d979c633d4.png)

It's doesn't work at all.

**Comment by turbio** [comment]
From the message right above the error it looks like you don't have python2/3 support in your vim. You'll have to make sure python works to use Bracey.

I'll update the message to make that a bit more clear.

**Comment by turbio** [comment]
closing as this doesn't look like a bug in Bracey
