### ISSUE TITLE
Disabel highlightening in webpage

### ISSUE THREAD

**Issue by BernH4** [turbio/bracey.vim#30]
Bracey is highlightening in the page where i currently are in the html file. How can i disable and renable this? Also is there a manual with all the commands of bracey explained? 
Also im fairly new to dev stuff, let me know if opening an issue for that is wrong and what i should have done else.

**Comment by turbio** [comment]
The usage and configuration sections of the readme should cover everything https://github.com/turbio/bracey.vim#usage. There is no vim help doc unfortunately. It sounds like you want to run `BraceyStop` and `Bracey` to stop and start it.
