### ISSUE TITLE
bracey_refresh_on_save=1 should take effect on javascript files

### ISSUE THREAD

**Issue by DONofDESTROY** [turbio/bracey.vim#39]
Hey guys 
thanks for the project
the variable `let g:bracey_refresh_on_save =1` doesn't take effect on javascript files
this solves #37 cause reloading obviously clears the console (thats how the live server works) 
**Whyyyyy....**
so in case some one is playing with DOM, 
```javascript
val = list.children[0].id = "test";
```
instead he needs to change the other element so he changes the line into
```javascript
val = list.children[1].id = "test";
```
but the children[0] still has the **id=test**

however this is not a problem in html and css they reload the stuff correctly

**Comment by DONofDESTROY** [comment]
I am really sorry this is working now Idk How it is working now

**Comment by DONofDESTROY** [comment]
This problem is solved by adding these in init.vim
```vim
if g:bracey_refresh_on_save
  autocmd BufWritePost *.js call bracey#reload()
endif
```

**Comment by turbio** [comment]
@DONofDESTROY thanks for following up with a solution. I'll add your suggestion to the readme when I get a chance.

**Comment by DONofDESTROY** [comment]
@turbio if this feature is worth enough, I will be happy to make this  as separate variable ex `g:bracey_refresh_js_on_save` and create doc for this, as a PR

**Comment by turbio** [comment]
that sounds great! would be much appreciated.

**Comment by DONofDESTROY** [comment]
@turbio I created something but the user need to disable the `bracey_eval_on_save` since it is trying to do same thing on `console.log()` so the `console.log()`(it also affects alert()) is executed twice mainly on  the javascript files but on the other hand the DOM elements are working as excepted
