### ISSUE TITLE
npm install error

### ISSUE THREAD

**Issue by grants** [turbio/bracey.vim#45]
When I use "npm install --prefix server", I got this error:

```
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

found 0 vulnerabilities
```

So my server didn't work. Could you tell me how to fix this ?

**Comment by turbio** [comment]
That snippet of npm's output looks fine, if the exit code is indeed non-zero could you post all of its output. I'm guessing the issue might not be with installing deps, could you post any errors you get while trying to start Bracey.
Thnx!

**Comment by grants** [comment]
You're right, this WARN message didn't affect bracey server, I started it successfully. So I guess this is a false alert.
