### ISSUE TITLE
Bracey depends on python? It won't run when instructions are followed.

### ISSUE THREAD

**Issue by JwanKhalaf** [turbio/bracey.vim#53]
Hello

I tried to follow the instructions, but when I run `:Bracey` I get:

![image](https://user-images.githubusercontent.com/42877376/109416132-42fec880-79b4-11eb-9142-4a1c16be875c.png)

I am using `vim-plug` and when I installed the Bracey plugin using `Plug 'turbio/bracey.vim', {'do': 'npm install --prefix server'}` it said that it installed and that the post-installation hook was OK too.

Yet it isn't running. Has something been missed from the instructions?

I'm on Manjaro Linux.

**Comment by turbio** [comment]
yup, Bracey needs vim to be built with python support. The steps to get this setup will depend on your OS, most distros package vim with python support these days.

**Comment by turbio** [comment]
Closing since this is expected and outside of Bracey's responsibility.

**Comment by Davidgonz-maker** [comment]
Hello, this works for me:
`sudo apt install python3-pip`
`python3 -m pip install neovim`

**Comment by AbdeltwabMF** [comment]
@JwanKhalaf 
Run this line in your terminal and it shall works.
```shell
python3 -m pip install --user --upgrade pynvim
```

**Comment by Meaticus22** [comment]
> @JwanKhalaf Run this line in your terminal and it shall works.
> 
> ```shell
> python3 -m pip install --user --upgrade pynvim
> ```

python3 -m pip install --user --upgrade pynvim 
usage: ptpython [-h] [--vi] [-i] [--asyncio] [--light-bg] [--dark-bg] [--config-file CONFIG_FILE]
                [--history-file HISTORY_FILE] [-V]
                [args ...]
ptpython: error: unrecognized arguments: -m --user --upgrade pynvim
