### ISSUE TITLE
is there available  for neovim

### ISSUE THREAD

**Issue by alavaelian** [turbio/bracey.vim#72]
is there a version for neovim or an alternative

**Comment by proffapt** [comment]
yes this works on neovim too; just like a charm

**Comment by thepenguinthatwants** [comment]
bracey error: <urlopen error [Errno 111] Connection refused>

I am just getting this error

**Comment by FarooqFarooqi** [comment]
go to the folder where bracey is installed with your plugin manager then run command

npm install --prefix server

**Comment by louis010f** [comment]
![image](https://user-images.githubusercontent.com/71259902/230626706-09641c12-1f66-4ade-bcd0-7c65917b031f.png)
How can i fix it, i need to this plugin

**Comment by alavaelian** [comment]
man thanks for the answer

**Comment by alavaelian** [comment]
> yes this works on neovim too; just like a charm

thanks for the answer

**Comment by ITProggeruz** [comment]
> ![image](https://user-images.githubusercontent.com/71259902/230626706-09641c12-1f66-4ade-bcd0-7c65917b031f.png) How can i fix it, i need to this plugin

learn to read, you need python
